import type { ArtifactRecord } from "../chatmem-memory/types";

type ArtifactsPanelProps = {
  artifacts: ArtifactRecord[];
  loading: boolean;
};

export default function ArtifactsPanel({ artifacts, loading }: ArtifactsPanelProps) {
  if (loading) {
    return (
      <section className="memory-panel">
        <div className="loading">
          <div className="spinner"></div>
        </div>
      </section>
    );
  }

  if (artifacts.length === 0) {
    return (
      <section className="memory-panel">
        <div className="empty-state">
          <div className="empty-state-icon">A</div>
          <div className="empty-state-text">No run artifacts are available for this repository yet.</div>
        </div>
      </section>
    );
  }

  return (
    <section className="memory-panel">
      <div className="memory-panel-header">
        <h3>Artifacts</h3>
        <p>Recent outputs generated by runs, including their type and current trust state.</p>
      </div>
      <div className="memory-card-list">
        {artifacts.map((artifact) => (
          <article key={artifact.artifact_id} className="memory-card">
            <div className="memory-card-header">
              <div>
                <strong>{artifact.title}</strong>
                <div className="memory-card-kind">{artifact.artifact_type}</div>
              </div>
              <span
                className={`timeline-pill artifact-trust-pill artifact-trust-${artifact.trust_state}`}
              >
                {artifact.trust_state}
              </span>
            </div>
            <p className="memory-card-copy">{artifact.summary}</p>
            <div className="timeline-meta-row">
              <span>Run: {artifact.run_id}</span>
              <span>Created: {artifact.created_at}</span>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
